### ISSUE TITLE
작성자의 정보도 기재되면 좋겠습니다.

### ISSUE THREAD

**Issue by webhacking** [of-course/of-course.github.io#2]
연재하는 대상자의 정보도 문서에 기재되면 좋을 것 같습니다.
Python 스터디 문서 작성하려고하는데, pull request 요청하면 될까요 ?

**Comment by Prev** [comment]
네 저야 사이트의 품질이 높아지니 좋지요 :)
서식 맞춰서 강의 작성 해 주시면 감사하겠습니다.

작성자란은 이후에라도 레이아웃을 수정하며 넣을 수도 있을 것 같습니다.
